In [1]:
import pandas as pd
df = pd.read_excel('Gene_evolve_pycopy.xlsx')

In [2]:
df

     Positiona Referenceb Queryc                  Typed       Locuse
0        859.0          G      T  NON_SYNONYMOUS_CODING   KV39_21610
1       2361.0          T      A      SYNONYMOUS_CODING   KV39_21610
2      15335.0          A      G             INTERGENIC            -
3      15356.0          A      G             INTERGENIC            -
4      30173.0          T      A  NON_SYNONYMOUS_CODING  KV39_032957
..         ...        ...    ...                    ...          ...
354  4569303.0          C      T      SYNONYMOUS_CODING   KV39_05160
355  4586056.0          T      C  NON_SYNONYMOUS_CODING   KV39_05070
356  4625079.0        GAA     GA            FRAME_SHIFT   KV39_17280
357  4636438.0          T      C             INTERGENIC            -
358  4660465.0          A      G      SYNONYMOUS_CODING   KV39_21745

[359 rows x 5 columns]

In [3]:
import entrezpy.esearch.esearcher
import urllib.request
import re
import sys
import os
os.system('clear')

In [10]:
def esearch (query):
    
    e = entrezpy.esearch.esearcher.Esearcher('esearcher', 'onyekao@iastate.edu')
    a = e.inquire({'db':'protein','term':query, 'retmax': 100, 'retmode':'text','rettype': 'fasta'})

    id = a.get_result().uids[0]
    contents = urllib.request.urlopen("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=protein&id=%s&rettype=gp&retmode=text"%id).read().decode('utf-8')

    product = re.search('product="([\w\- ]+)"', contents).group(1)
    region = re.search('region_name="([\w\- ]+)"', contents).group(1)
    return ('%s "%s" "%s"'%(query,product,region))

In [1]:
df['result']= df['Locuse'].apply(esearch)

NameError: name 'df' is not defined

In [9]:
df

,Positiona,Referenceb,Queryc,Typed,Locuse,result
0,859.0,G,T,NON_SYNONYMOUS_CODING,KV39_21610,"KV39_21610 ""aspartate kinase"" ""thrA"""
1,2361.0,T,A,SYNONYMOUS_CODING,KV39_21610,"KV39_21610 ""aspartate kinase"" ""thrA"""
2,15335.0,A,G,INTERGENIC,-,"- ""aspartate kinase"" ""thrA"""
3,15356.0,A,G,INTERGENIC,-,"- ""aspartate kinase"" ""thrA"""
4,30173.0,T,A,NON_SYNONYMOUS_CODING,KV39_032957,"KV39_032957 ""aspartate kinase"" ""thrA"""
...,...,...,...,...,...,...
354,4569303.0,C,T,SYNONYMOUS_CODING,KV39_05160,"KV39_05160 ""aspartate kinase"" ""thrA"""
355,4586056.0,T,C,NON_SYNONYMOUS_CODING,KV39_05070,"KV39_05070 ""aspartate kinase"" ""thrA"""
356,4625079.0,GAA,GA,FRAME_SHIFT,KV39_17280,"KV39_17280 ""aspartate kinase"" ""thrA"""
357,4636438.0,T,C,INTERGENIC,-,"- ""aspartate kinase"" ""thrA"""
358,4660465.0,A,G,SYNONYMOUS_CODING,KV39_21745,"KV39_21745 ""aspartate kinase"" ""thrA"""